### ISSUE TITLE
Sponsor Management

### ISSUE THREAD

**Issue by fakih** [lelionvert/socrates-team2#2]
- Add a new Sponsor
- Get a list of sponsors

**Comment by fakih** [comment]
Bug, An exception is raised when I add a sponsor :(
Exception in thread "main" java.lang.IllegalStateException
	at fr.socrates.domain.sponsor.Sponsor$SponsorBuilder.createSponsor(Sponsor.java:83)
	at fr.socrates.Main.createSponsor(Main.java:169)
	at fr.socrates.Main.main(Main.java:74)

**Comment by udebella** [comment]
@fakih "il y a des sponsors qui nous donnent leurs siret, d'autres qui nous donnent le siren. Le plus important pour moi est d'avoir le siren : on pourrait rendre obligatoire la saisie du siren (9 chiffres) et optionnel la saisie du siret ou le nic : numéro interne de classement pour éviter de saisir deux fois la même chose par contre quand je demande les infos sur le sponsor, je veux pas qu'on affiche le nic"
Sorry I did not translate the discussion we had on slack. But I think we need to keep track of that.

I'm now working on SIRET and SIREN. Can you give us examples where you need SIREN and SIRET?

* Relation between SIREN and SIRET : https://fr.wikipedia.org/wiki/Syst%C3%A8me_d%27identification_du_r%C3%A9pertoire_des_%C3%A9tablissements)

**Comment by fakih** [comment]
I dont need both. This information is used to create and edit contracts
